[package]
name = "sql-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
easy-macros = { path = "../../easy-macros", features = ["for-macro"] }
convert_case = "0.8.0"

[build-dependencies]
easy-macros = { path = "../../easy-macros", features = ["build"] }
